services:
  - type: web
    name: minsk-girls-club-bot
    runtime: python
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: CLUB_CHAT_LINK
        sync: false